name: OpenDCS initial build and test
on:
  pull_request:
    branches: [master]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:        
        platform: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: $${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: ant compile